#!/bin/bash
#
# Run 'make', saving all output into a file named LOG.
#
# usage:
#	MK  [args]   - runs make silently
#	MKV [args]   - runs make echoing commands
#
# Both versions print starting and ending timestamps to the terminal
# after 'make' completes.
#

# remember this so we know what to do
name="`basename $0`"

# starting timestamp
time1="`date`"

if [ "$name" = "MK" ]
then
	# run make, save output, check status
	echo -n + make $* '> LOG 2>&1 ... '
	if make $* > LOG 2>&1
	then
		echo done
	else
		echo check LOG for build errors
	fi
else
	# just do the make and save a copy of the output
	echo + make $* '2>&1 | tee LOG'
	make $* 2>&1 | tee LOG
fi

# ending timestamp
time2="`date`"

echo  Start: $time1
echo "End:  " $time2
