/*
** @file: pro100.c
**
** @author: Ryan Lembo-Ehms
**
** @brief: Pro100 device code
*/

#include <pci.h>
#include <device/cb.h>
#include <device/pro100.h>
#include <kmem.h>
#include <x86/ops.h>
#include <x86/pic.h>
#include <lib.h>
#include <support.h>
#include <cio.h>
#include <klib.h>

/*
** Macros for values used in in_/out_ functions
*/
#define BUS_MASTER      (1 << 2)
#define IO_SPACE        (1 << 0)
#define SOFTWARE_RESET  0x00
#define RU_START        0x0001
#define RU_LOAD_BASE    0x0006
#define CU_START        0x0010
#define CU_RESUME       0x0020
#define CU_LD_DUMP_ADR  0x0040
#define CU_DUMP         0x0050
#define CU_LOAD_BASE    0x0060
#define INT_MASK        0x0100
#define CNA_INT_MASK    0x2000

/*
** Intel 8255x Control/Status Register (CSR) Macros
** Offsets from the Pro100's I/O base address
*/
#define SCB_STATUS    0x00
#define SCB_COMMAND   0x02
#define SCB_POINTER   0x04
#define PORT          0x08

#define STAT_ACK      SCB_STATUS + 0x01

/*
** Interrupt flags set by the NIC inside the
** SCB Status word. These are called the STAT/ACK
** bits and only live in the upper byte of the word
**
** Bits 7:2 and bit 0 are used. Bit 1 is reserved
*/
#define CX_TNO_INT    0x80
#define FR_INT        0x40
#define CNA_INT       0x20
#define RNR_INT       0x10
#define MDI_INT       0x08
#define SWI_INT       0x04
#define FCP_INT       0x01

/*
** Command Block (CB) Macros
*/
#define CB_CMD_ACCEPT 0x0000
#define CB_CMD_NOP    0x0000
#define CB_CMD_IAS    0x0001
#define CB_CMD_CFG    0x0002
#define CB_CMD_TX     0x0004
#define CB_CMD_SF     0x0008
#define CB_CMD_EL     0x8000  // Any cb with this bit set is the last cb
#define TXCB_EOF      0x8000
#define CMD_SUCCESS   0xA000
#define RX_SUCCESS    0xA000
#define RX_EVENT      0xBFFF

// Global Pro100 pointer
pro100_t *pro100;

void pro100_outl(uint32_t offset, uint32_t val) {
  outl(pro100->io_base_addr + offset, val);
}

void pro100_outw(uint32_t offset, uint16_t val) {
  outw(pro100->io_base_addr + offset, val);
}

void pro100_outb(uint32_t offset, uint8_t val) {
  outb(pro100->io_base_addr + offset, val);
}

uint32_t pro100_inl(uint32_t offset) {
  return inl(pro100->io_base_addr + offset);
}

uint16_t pro100_inw(uint32_t offset) {
  return inw(pro100->io_base_addr + offset);
}

uint8_t pro100_inb(uint32_t offset) {
  return inb(pro100->io_base_addr + offset);
}

/**
** pro100_isr
**
** Interrupt handler for interrupts generated by the Pro100
**
** @param vector - vector number for the interrupt that occurred
** @param code -  error code, or a dummy value
**
** For more detailed information about the Pro100's interrupt flags, visit
** page 43 of the Intel 8255x datasheet.
*/
void pro100_isr(int vector, int code) {

  uint8_t flags = pro100_inb(STAT_ACK);
  
#ifdef DEBUG_NIC
  cio_printf("\n** Pro100 ISR! vector=0x%02x, code=%d\n",
      (unsigned int) vector, code);

  // Print the STAT/ACK bits so we can see which interrupt flag is set
  cio_printf("STAT/ACK bits=%x\n", flags);
#endif

  // We're probably in this ISR because a frame was recieved
  // Frame recieved == FR
  if (flags & FR_INT) {

    // Start by acking the interrupt
    pro100_outb(STAT_ACK, FR_INT);
    flags &= ~FR_INT;

    // Now process the recieved frame
    pro100_recieve();
  }

  // The other main interrupt flag is the CNA flag, which gets set
  // everytime the command unit (CU) leaves the active state.
  if (flags & CNA_INT) {
    pro100_outb(STAT_ACK, CNA_INT);
    flags &= ~CNA_INT;
  }

  // This will acknowledge ALL remaining interrupt flags raised by the NIC,
  // even though we aren't handling them all.
  pro100_outb(STAT_ACK, flags);
  
  // Tell the PIC we're done
  outb(PIC2_CMD, PIC_EOI);
  outb(PIC1_CMD, PIC_EOI);
}


/*
** pro100_address_setup
**
** Creates a individual address setup command block, gives it to the NIC,
** and issues a CU_START command to process the command block
*/
void pro100_address_setup(void) {

  // Build the individual address command 
  cb_ias_t *cb_ias = (cb_ias_t *) km_page_alloc(1);
  cb_ias->hdr.status = 0;
  cb_ias->hdr.command = CB_CMD_IAS | CB_CMD_EL;
  cb_ias->hdr.link = 0xFFFFFFFF;
  
  // Set an arbitrary mac address
#ifdef NODE_1
  cb_ias->mac[0] = 0xA2;
  cb_ias->mac[1] = 0xB3;
  cb_ias->mac[2] = 0xC4;
  cb_ias->mac[3] = 0xD5;
  cb_ias->mac[4] = 0xE6;
  cb_ias->mac[5] = 0xF7;
#else
  cb_ias->mac[0] = 0x2A;
  cb_ias->mac[1] = 0x3B;
  cb_ias->mac[2] = 0x4C;
  cb_ias->mac[3] = 0x5D;
  cb_ias->mac[4] = 0x6E;
  cb_ias->mac[5] = 0x7F;
#endif 

  // Copy this 6-byte mac address to the Pro100 device structure in memory
  // Important later for building Tx frames
  memcpy(pro100->mac, cb_ias->mac, 6);

  pro100_outl(SCB_POINTER, (uint32_t) cb_ias);
  pro100_outw(SCB_COMMAND, CU_START | CNA_INT_MASK);
  
  while (!(cb_ias->hdr.status & CMD_SUCCESS)) {
    // wait until the command has been accepted by the NIC
  }

#ifdef DEBUG_NIC
  char buf[128];
  sprint(buf, "Command block status=0x%04x\n",
               cb_ias->hdr.status);
  cio_printf(buf);
  delay(DELAY_1_SEC);
#endif
  
  // Slight delay before freeing just to be safe
  delay(10); 

  km_page_free(cb_ias);
}


/*
** pro100_configure
**
** Creates a configure command block, gives it to the NIC,
** and issues a CU_START command to process the command block
*/
void pro100_configure(void) {
  
  cb_config_t *cb = (cb_config_t *) km_page_alloc(1);
  cb->hdr.status = 0;
  cb->hdr.command = CB_CMD_CFG | CB_CMD_EL; 
  cb->hdr.link = 0xFFFFFFFF;
  
  // Some recommended values in the config map are 0,
  // so just clear everything then set individual bytes.
  memset(cb->config, N_CONFIG_BYTES, 0);

  // Set the fundamental operating parameters of the Pro100
  // Uses the recommended settings from the datasheet
  cb->config[0]   = 0x16;  // 22 bytes configuration map
  cb->config[1]   = 0x08;  // FIFO Tx/Rx limits
  cb->config[3]   = 0x01;  // Read alignment
  cb->config[6]   = 0xB0;  // Standard TxCB
  cb->config[7]   = 0x00;  // Keep bad frames
  cb->config[8]   = 0x01;  // PHY MII mode
  cb->config[10]  = 0x28;  // 7-byte preamble, NSAI
  cb->config[12]  = 0x60;  // IFS
  cb->config[14]  = 0xF2;  // For backwards compatibility
  cb->config[18]  = 0xF3;  // Padding + Stripping of frames
  cb->config[19]  = 0x80;  // Mandatory bits for 82559
  cb->config[20]  = 0x3F;  // Mandatory bits for 82559
  cb->config[21]  = 0x05;  // Disables Multicast all

  pro100_outl(SCB_POINTER, (uint32_t) cb);
  pro100_outw(SCB_COMMAND, CU_START | CNA_INT_MASK);

  while(!(cb->hdr.status & CMD_SUCCESS)) {
    // wait until the command has been accepted
  }
  
#ifdef DEBUG_NIC
  char buf[128];
  sprint(buf, "Command block status=0x%04x\n",
               cb->hdr.status);
  cio_printf(buf);
  delay(DELAY_1_SEC);
#endif

  // Configure command is done, free the command block memory
  km_page_free(cb);
}


/*
** pro100_access_enable
**
** Enables I/O communication from the host CPU to the NIC
*/
void pro100_access_enable(void) {
  
  // 0x4 is the offset of the register with command 
  // Refer to the pci_dev_t struct in include/pci.h for 
  // offsets of each header register.
  uint32_t command = pci_cfgspace_readl(pro100->pci_dev, 0x4);

#ifdef DEBUG_PCI
  char buf[128];
  sprint(buf, "Pro100 PCI command reg=0x%x\n", command);
  cio_printf(buf);
  delay( DELAY_1_SEC );
#endif

  command = command | BUS_MASTER | IO_SPACE;

  pci_cfgspace_writel(pro100->pci_dev, 0x4, command); 

#ifdef DEBUG_PCI
  command = pci_cfgspace_readl(pro100->pci_dev, 0x4);
  sprint(buf, "Pro100 PCI command reg=0x%x\n", command);
  cio_printf(buf);
  delay( DELAY_1_SEC );
#endif

}

 
/*
** pro100_rx_init
**
** Creates the first (and only) RFD, gives it to the NIC
** and issues an RU_START command to the NIC
*/
void pro100_rx_init(void) {
  
  // Build the RFD 
  rfd_t *rfd = (rfd_t *) km_page_alloc(1);
  rfd->hdr.status = 0; 
  rfd->hdr.command = CB_CMD_EL;
  rfd->hdr.link = 0xFFFFFFFF;

  // This memory should be cleared so it accurately reports rx info
  memset(&rfd->actual_count, sizeof(uint32_t), 0);

  rfd->size = PAYLOAD_SIZE;
 
  // Tell device it is ready to recieve frames
  pro100_outl(SCB_POINTER, (uint32_t) rfd);
  pro100_outw(SCB_COMMAND, RU_START | CNA_INT_MASK);

  delay(10);

  // Copy this RFD to the logical device so we can access it later
  pro100->rfd = rfd;
}


/*
** pro100_recieve
**
** Parses a recieved ethernet frame and prints the data.
**
** Called in pro100_isr
*/
void pro100_recieve(void) {
  // Check how many bytes were recieved
  uint32_t byte_count = pro100->rfd->actual_count;
#ifdef DEBUG_NIC
  cio_printf("\n** Recieved %d bytes!\n", byte_count);
#endif
  // Now print the payload
}


/*
** pro100_transmit
**
** Builds a TxCB, constructs an ethernet packet, and
** issues a transmit command to the NIC
*/
void pro100_transmit(char *data) {
 
  // Build the TxCB
  tx_cb_t *tx_cb = (tx_cb_t *) km_page_alloc(1);
  tx_cb->hdr.status = 0;
  tx_cb->hdr.command = CB_CMD_TX | CB_CMD_EL;
  tx_cb->hdr.link = 0xFFFFFFFF;

  tx_cb->tbd_addr = 0xFFFFFFFF;
  tx_cb->tx_threshold = 0x01;
  tx_cb->tbd_number = 0;
 
  /*
  ** Begin packet construction
  */ 
  uint8_t *p = tx_cb->packet;

  // Destination MAC. Broadcast to everything on the network
  p[0] = 0xFF;
  p[1] = 0xFF;
  p[2] = 0xFF;
  p[3] = 0xFF;
  p[4] = 0xFF;
  p[5] = 0xFF;
  
  // Source MAC. Not inserted by NIC, per settings from config command
  memcpy(&p[6], pro100->mac, 6);
  
  uint16_t len_data = (uint16_t) strlen(data);

  // Length/Type field of ethernet frame header. 2 bytes long
  p[12] = 0x08;
  p[13] = 0x00;

  // Payload
  // config map byte 18 bits 1:0 means NIC should handle packet
  // padding and stripping, so SHOULD be fine if data is shorter
  // than minimum required ethernet frame length 
  memcpy(&p[14], data, len_data);
  
  // 14 = 2 * 6-byte MAC addresses, 2-byte Length/Type field
  // Since the entire frame is in one TCB, set the EOF bit too
  tx_cb->byte_count = (ETH_FRAME_HDR + len_data) | TXCB_EOF;

  /*
  ** End of packet construction
  */

  // Begin transmission
  pro100_outl(SCB_POINTER, (uint32_t) tx_cb);
  pro100_outw(SCB_COMMAND, CU_START);
  
  // Poll to see if entire frame has been sent to NIC's transmit FIFO
  while(!(tx_cb->hdr.status & CMD_SUCCESS)) {
    // wait
  }

  // Once the entire frame is given to the NIC, we can free this memory
  km_page_free(tx_cb);
}

/*
** pro100_check_counter
**
** Checks a specific statistical counter
**
** @param offset - The offset of the statiscal counter from the first counter
**
** @return The new value of the statiscal counter if there was a change
**         since the last dump, otherwise -1.
*/
int pro100_check_counter(uint32_t offset) {

  uint32_t index = offset / 4;  // Offests are Dword aligned
  uint32_t val = pro100->stat_counters[index];
  
  pro100_counter_dump();
  delay(100);

  // Check if the counter shows something new
  uint32_t new_val = pro100->stat_counters[index];
  if (val != new_val) {
    return new_val;
  }

  // Nothing changed since the last dump
  return -1;
}


/*
** pro100_counter_dump
**
** Issues a Dump Statistical Counters command to the NIC
**
*/
void pro100_counter_dump(void) {
  pro100_outw(SCB_COMMAND, CU_DUMP | CNA_INT_MASK);
}


/*
** pro100_init
**
** Initialization routine for the Pro100 NIC.
** Performs a software reset, then configures
** the NIC. Once this routine returns, the
** NIC should be ready to transmit and recieve
** ethernet frames
*/
void pro100_init() {
#ifdef DEBUG_NIC
  char buf[128];
#endif
  
  pro100 = (pro100_t *) km_page_alloc(1);

  // Initialize the pro100's fields
  pro100->pci_dev = pci_dev_pro100;
  pro100->io_base_addr = pci_get_bar(pro100->pci_dev->hdr, PCI_BAR_IO) & PCI_BAR_IO_MASK;

  pro100_access_enable();

  // Always start with a software reset
  pro100_outl(pro100->io_base_addr + PORT, SOFTWARE_RESET);
  
  // Delay at least 10us after a reset
  delay(100);

  // Set the CU to linear addressing mode
  pro100_outl(SCB_POINTER, 0x00000000);
  pro100_outw(SCB_COMMAND, CU_LOAD_BASE | CNA_INT_MASK);

  // Set the RU to linear addressing mode
  pro100_outl(SCB_POINTER, 0x00000000);
  pro100_outw(SCB_COMMAND, RU_LOAD_BASE | CNA_INT_MASK);

  // Let the NIC know where to dump registers to
  pro100_outl(SCB_POINTER, (uint32_t) pro100->stat_counters);
  pro100_outw(SCB_COMMAND, CU_LD_DUMP_ADR | CNA_INT_MASK);

  pro100_configure();

  pro100_address_setup();

  pro100_rx_init();

#ifdef DEBUG_NIC 
  uint16_t scb_status = pro100_inw(SCB_STATUS);
  sprint(buf, "SCB Status=0x%04x\n", scb_status);
  cio_printf(buf);
  delay( DELAY_1_SEC );

  uint16_t scb_command = pro100_inw(SCB_COMMAND);
  sprint(buf, "SCB Command=0x%04x\n", scb_command);
  cio_printf(buf);
  delay( DELAY_1_SEC );
#endif

  // Lastly, install the ISR that handles interrupts
  // generated by the NIC
  install_isr(VEC_NIC, &pro100_isr);  

/*
** The following code exists solely for the project demonstration.
**
** The goal was to have frame transmission be done by a user process, and 
** recieving be handled in an interrupt. This is difficult to test because
** of the clock bug, so Tx/Rx will be tested in the kernel instead.
*/
#ifdef BAD_CLOCK
#if defined(NODE_1) && defined(DEBUG_NIC)
  
  // An arbitrary 64-byte message
  char* msg = "AAAAAAAAbbbbbbbbCCCCCCCCddddddddEEEEEEEEffffffffGGGGGGGGhhhhhhhh\0";
  pro100_transmit(msg);
  delay(DELAY_2_SEC);

  int tx_ok = pro100_check_counter(0x00);
  sprint(buf, "** Transmit OK counter=%d\n", tx_ok);
  cio_printf(buf);

#elif defined(NODE_2) && defined(DEBUG_NIC)

  while(!(pro100->rfd->hdr.status & RX_EVENT)) {
    sprint(buf, "** RFD status=0x%04x\n", pro100->rfd->hdr.status);
    cio_printf(buf); 
    delay(DELAY_2_SEC);
  }
  
  if (pro100->rfd->hdr.status & RX_SUCCESS) {
    pro100_recieve();
  }
#endif /* NODE_1/2  */
#endif /* BAD_CLOCK */
}

